model: "QuartzNet"
sample_rate: 16000

AudioToTextDataLayer:
    max_duration: 16.7
    trim_silence: true

    train:
        shuffle: true

    eval:
        shuffle: false
        max_duration: null

AudioPreprocessing:
    window_size: 0.02
    window_stride: 0.01
    window: "hann"
    normalize: "per_feature"
    n_fft: 512
    features: 64
    feat_type: "logfbank"
    dither: 0.00001
    pad_to: 16
    stft_conv: true

SpectrogramAugmentation:
    rect_masks: 5
    rect_time: 120
    rect_freq: 50

JasperEncoder:
    activation: "relu"
    conv_mask: true

    jasper:
      - filters: 256
        repeat: 1
        kernel: [33]
        stride: [2]
        dilation: [1]
        dropout: 0.0
        residual: false
        separable: true

      - filters: 256
        repeat: 5
        kernel: [33]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 256
        repeat: 5
        kernel: [33]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 256
        repeat: 5
        kernel: [33]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 256
        repeat: 5
        kernel: [39]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 256
        repeat: 5
        kernel: [39]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 256
        repeat: 5
        kernel: [39]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 5
        kernel: [51]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 5
        kernel: [51]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 5
        kernel: [51]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 5
        kernel: [63]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 5
        kernel: [63]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 5
        kernel: [63]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 5
        kernel: [75]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 5
        kernel: [75]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 5
        kernel: [75]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 1
        kernel: [87]
        stride: [1]
        dilation: [2]
        dropout: 0.0
        residual: false
        separable: true

      - filters: 1024
        repeat: 1
        kernel: [1]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: false

labels: [" ", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
         "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "'"]

IGNORE_MISSING_KEYS:
  value : true

input_configuration_activation:
  bit_width : 8
  quant_type : "QuantType.FP"
  scaling_impl_type : "STATS"
  scaling_stats_op : "MAX"
  scaling_min_val : 2e-8
  max_val : 20
  min_val : -20

firstBlock_configuration_activation:
  bit_width : 8
  quant_type : "QuantType.FP"
  scaling_impl_type : "STATS"
  scaling_stats_op : "MAX"
  scaling_min_val : 2e-8
  max_val : 20
  min_val : -20


firstBlock_configuration_weight:
  weight_bit_width : 8
  weight_quant_type : "QuantType.FP"
  weight_narrow_range : true
  weight_scaling_impl_type : "STATS"
  weight_scaling_stats_op : "MAX"
  weight_scaling_min_val : 2e-8
  bias : false
  bias_bit_width : 8
  bias_quant_type : "QuantType.FP"
  bias_narrow_range : false
  compute_output_scale : false
  compute_output_bit_width : false

jasperBlocks_configuration_activation:
  bit_width : 8
  quant_type : "QuantType.FP"
  scaling_impl_type : "STATS"
  scaling_stats_op : "MAX"
  scaling_min_val : 2e-8
  max_val : 20


jasperBlocks_configuration_weight:
  weight_bit_width : 8
  weight_quant_type : "QuantType.FP"
  weight_narrow_range : true
  weight_scaling_impl_type : "STATS"
  weight_scaling_stats_op : "MAX"
  weight_scaling_min_val : 2e-8
  bias : false
  bias_bit_width : 8
  bias_quant_type : "QuantType.FP"
  bias_narrow_range : false
  compute_output_scale : false
  compute_output_bit_width : false


lastBlock_configuration_weight:
  weight_bit_width : 8
  weight_quant_type : "QuantType.FP"
  weight_narrow_range : true
  weight_scaling_impl_type : "STATS"
  weight_scaling_stats_op : "MAX"
  weight_scaling_min_val : 2e-8
  bias : true
  bias_bit_width : 8
  bias_quant_type : "QuantType.FP"
  bias_narrow_range : false
  compute_output_scale : false
  compute_output_bit_width : false

jasperBlocks_configuration_residual:
  bit_width : 8
  quant_type : "QuantType.FP"
  scaling_impl_type : "STATS"
  scaling_stats_op : "MAX"
  scaling_min_val : 2e-8
  max_val : 20
  min_val : -20
